import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { PushIn } from 'pushin'
import { useEffect, useRef } from 'react'

const Home: NextPage = () => {
  const pushInContainer = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const pushIn = new PushIn(pushInContainer.current!);
    pushIn.start();

    return () => pushIn.destroy();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="pushin" ref={pushInContainer}>
          <div className="pushin-scene">
            <div className="pushin-layer">This is the first layer you'll see.</div>
            <div className="pushin-layer">
              This is a second layer, which will be positioned behind the first one <a href="#">but links should work properly!</a>.
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
